// Project info

name := "scalaflect"

organization := "au.id.jazzy"

// The version comes from version.sbt, and is generated by the release plugin

scalaVersion := "2.9.1"

// Dependencies

libraryDependencies ++= Seq(
    "org.ow2.asm" % "asm" % "4.0"
)

// Test dependencies

libraryDependencies ++= Seq(
    "org.specs2" %% "specs2" % "1.8.2" % "test"
)

